services:
  - type: web
    name: "Nailab Backend"
    env: ruby
    branch: main
    plan: starter
    buildCommand: |
      bundle install --jobs 4 --retry 3
      npm install
      bundle exec rails assets:precompile
      bundle exec rails tailwindcss:build
    preDeployCommand: |
      bundle exec rails db:migrate
    startCommand: bundle exec puma -C config/puma.rb
    autoDeploy: true
    healthCheckPath: "/up"
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RACK_ENV
        value: production
      - key: RAILS_SERVE_STATIC_FILES
        value: "true"
      - key: RAILS_LOG_TO_STDOUT
        value: "true"
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: nailab-db
          property: connectionString

databases:
  - name: nailab-db
    plan: starter
